### ISSUE TITLE
new endpoint

### ISSUE THREAD

**Issue by liujinf** [wso2-attic/product-gw#44]
Hi,
I am working on implementing new endpoint(about redis), generated bundle and put it in osgi/dropins, and add line on camel-context.xml, like this:
<bean id="tis-redis" class="tis.gateway.component.redis.TisredisComponent"/>
but error:
Caused by: java.lang.ClassNotFoundException: tis.gateway.component.redis.TisredisComponent

We think bundle don't load successfully. What can we do?

Thanks.

liuhaif

**Comment by liuhaif** [comment]
It's OK by bundles.info.
Maybe 1.0.0.RC1 is OK. We will test it.
